// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: calc_engine/v1/calc_engine.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *GetSumRequest) Reset() {
	*x = GetSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_engine_v1_calc_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumRequest) ProtoMessage() {}

func (x *GetSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_engine_v1_calc_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumRequest.ProtoReflect.Descriptor instead.
func (*GetSumRequest) Descriptor() ([]byte, []int) {
	return file_calc_engine_v1_calc_engine_proto_rawDescGZIP(), []int{0}
}

func (x *GetSumRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *GetSumRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type GetSumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int64 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *GetSumReply) Reset() {
	*x = GetSumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_engine_v1_calc_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumReply) ProtoMessage() {}

func (x *GetSumReply) ProtoReflect() protoreflect.Message {
	mi := &file_calc_engine_v1_calc_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumReply.ProtoReflect.Descriptor instead.
func (*GetSumReply) Descriptor() ([]byte, []int) {
	return file_calc_engine_v1_calc_engine_proto_rawDescGZIP(), []int{1}
}

func (x *GetSumReply) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_calc_engine_v1_calc_engine_proto protoreflect.FileDescriptor

var file_calc_engine_v1_calc_engine_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x62, 0x22, 0x1f, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73,
	0x75, 0x6d, 0x32, 0x70, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x12, 0x62, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x73, 0x75, 0x6d, 0x2f, 0x7b, 0x61, 0x7d,
	0x2f, 0x7b, 0x62, 0x7d, 0x42, 0x3c, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x24, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calc_engine_v1_calc_engine_proto_rawDescOnce sync.Once
	file_calc_engine_v1_calc_engine_proto_rawDescData = file_calc_engine_v1_calc_engine_proto_rawDesc
)

func file_calc_engine_v1_calc_engine_proto_rawDescGZIP() []byte {
	file_calc_engine_v1_calc_engine_proto_rawDescOnce.Do(func() {
		file_calc_engine_v1_calc_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_calc_engine_v1_calc_engine_proto_rawDescData)
	})
	return file_calc_engine_v1_calc_engine_proto_rawDescData
}

var file_calc_engine_v1_calc_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calc_engine_v1_calc_engine_proto_goTypes = []any{
	(*GetSumRequest)(nil), // 0: api.calc_engine.v1.getSumRequest
	(*GetSumReply)(nil),   // 1: api.calc_engine.v1.getSumReply
}
var file_calc_engine_v1_calc_engine_proto_depIdxs = []int32{
	0, // 0: api.calc_engine.v1.CalcEngine.getSum:input_type -> api.calc_engine.v1.getSumRequest
	1, // 1: api.calc_engine.v1.CalcEngine.getSum:output_type -> api.calc_engine.v1.getSumReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calc_engine_v1_calc_engine_proto_init() }
func file_calc_engine_v1_calc_engine_proto_init() {
	if File_calc_engine_v1_calc_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calc_engine_v1_calc_engine_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calc_engine_v1_calc_engine_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calc_engine_v1_calc_engine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calc_engine_v1_calc_engine_proto_goTypes,
		DependencyIndexes: file_calc_engine_v1_calc_engine_proto_depIdxs,
		MessageInfos:      file_calc_engine_v1_calc_engine_proto_msgTypes,
	}.Build()
	File_calc_engine_v1_calc_engine_proto = out.File
	file_calc_engine_v1_calc_engine_proto_rawDesc = nil
	file_calc_engine_v1_calc_engine_proto_goTypes = nil
	file_calc_engine_v1_calc_engine_proto_depIdxs = nil
}
